### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by DingoEatingFuzz** [lytics/jstag#32]
# Roadmap

## High-level Goals
1. Make the library stable for development
2. Reduce the total filesize
3. Reduce the number of http requests
4. Make the jstag API user-friendly

### 1. Rewrite the core of jstag

Rewriting the core of jstag will give us a chance to write the library with testing and code coverage in mind. It will also give us a chance to consider the API as it currently stands. When rewriting the core, all four goals will be held in mind.

This is a large first milestone, but it is also extremely important. Although the jstag of today allows for web personalization to work, it does so in a hacky manner. The poor performance of jstag has already been brought up externally. Before marching down the road of more personalization capacity, we need to address core jstag issues.

#### TODO
  - [ ] Review the current state of of the library
  - [ ] Address serious JS issues (cross-browser bugs, unguarded edge cases, async oddities, etc.)
  - [ ] Refactor as necessary for complete unit testing
  - [ ] Instrument with code coverage
  - [ ] Add versioned build pipeline

### 2. Validate the core rewrite

Once the core has been rewritten, since the previous core did not have tests, the rewrite must be validated by comparing it against a production instance of jstag. The plan is to run old jstag and new jstag on the Lytics app side-by-side and compare all requests for anomalies.

#### TODO
  - [ ] Add a `noConflict` option to the library
  - [ ] Add the new library to webadmin (for testing in depth)
  - [ ] Review all messages in a ~24 hour window
  - [ ] Proxy the new library onto customer sites (for testing in breadth)
  - [ ] Address issues that arise

### 3. Extend the library API to have a low-level understanding of Campaigns

Once the core has been validated, it's safe to extend the behavior to facilitate upcoming product features. Namely low-level interaction with our Campaigns API.

#### TODO
  - [ ] Request the current entity via the Lytics API
  - [ ] Request the current campaigns via the Lytics API
  - [ ] Provide new methods for interacting with campaigns
  	 - [ ] `currentCampaigns()` returns a list of campaigns that the current user is in
  	 - [ ] `memberOf(:campaign, :variation)` returns true when the current user is in the campaign
  	 - [ ] `trackImpression(:campaign, :variation, callback)` sends an impression event to the collector (fails if the user isn't a member of the campaign and variation)
  	 - [ ] `trackConversion(:campaign, :variation, callback)` sends a conversion event to the collector (fails if the user isn't a member of the campaign and variation) 

### 4. Rollout the core rewrite + API extensions

Once the core has been validated and improved, it's safe to rollout through lio.js. Since it will be versioned, this can be done account by account. Encouraging opt-in should be easy, considering the new version will have features the old version doesn't.

#### TODO
  - [ ] Instrument jstag API usage
  - [ ] Update lio.js to include the new jstag version
  - [ ] Use this new build for accounts that opt-in (encourage opt-in)

### 5. Merge the jstag and outlio projects #25 

By merging these two projects we get to use the jstag testing and coverage frameworks for the third-party integration code with the added benefit of reducing http requests.

#### TODO
  - [ ] Create an improved, extendable integration type in jstag for handling the integration state machine
  - [ ] Support reading and writing data from and to integrations
  - [ ] Sunset outlio.js

### 6. Support custom builds per account

Since no account is likely to use every feature, allowing jstag builds to be configurable in webadmin can go a long way to reduce the footprint of the tracker. Everything would be default on, and the truly concerned can trim fat from there.

  - [ ] Make the jstag build customizable (e.g., `./build < config.json`)
  - [ ] Invoke jstag build from lio based on a request made by webadmin

### 7. vFuture

It's likely that there will be more work discovered or thought of by this point, but it isn't helpful to plan it out yet.
